
/* Automatic generated by hsk-garen */
import Vue from 'vue';
import Router from 'vue-router';
Vue.use(Router);

let routes = [
{
  path: '/lock',
  name: 'lock',
  component: resolve => {
    require.ensure([], () => {
      resolve(require('../../page/lock/lock.vue'))
    }, 'lock');
  }
},{
  path: '/404',
  name: '404',
  component: resolve => {
    require.ensure([], () => {
      resolve(require('../../page/404/404.vue'))
    }, '404');
  }
},{
  path: '/login',
  name: 'login',
  component: resolve => {
    require.ensure([], () => {
      resolve(require('../../page/login/login.vue'))
    }, 'login');
  }
},{
  path: '/',
  component: resolve => {
    require.ensure([], () => {
      resolve(require('../../page/main_$parent/layout/layout.vue'))
    }, '$base');
  },
  children: [
{
  path: '',
  name: 'main',
  component: resolve => {
    require.ensure([], () => {
      resolve(require('../../page/main_$parent/main.vue'))
    }, 'main');
  }
},{
  path: '/category',
  name: 'mainCategory',
  component: resolve => {
    require.ensure([], () => {
      resolve(require('../../page/main_$parent/category/category.vue'))
    }, 'mainCategory');
  }
}
  ]
}
];

import _base from './base';
routes = routes.concat(_base);

export default new Router({routes})
