/* Automatic generated by hsk-garen */
import _style from "./style";
import _system from "./system";
import _vue from "./vue";

export let style = _style;
export let system = _system;
export let vue = _vue;
